=== gaowenhui/eam23/webroot/pages/eam2/zccz/evalKnow/dynamic-form.dtd
<!ENTITY % Id "CDATA">
<!ENTITY % RenderType "(normal|readonly|disable)">
<!ENTITY % UserId "CDATA">
<!ENTITY % RoleId "CDATA">
<!ENTITY % DeptId "CDATA">

<!ELEMENT form-config (state-group) >

<!ELEMENT state-group (state*) >

<!ELEMENT state (component*) >
<!ATTLIST state         id               %Id;                #IMPLIED>

<!ELEMENT component (#PCDATA) >
<!ATTLIST component     id               %Id;                #IMPLIED>
<!ATTLIST component     renderType       %RenderType;        #IMPLIED>
<!ATTLIST component     userId           %UserId;            #IMPLIED>
<!ATTLIST component     roleId           %RoleId;            #IMPLIED>
<!ATTLIST component     deptId           %DeptId;            #IMPLIED>

=== gaowenhui/eam23/webroot/pages/eam2/kpgl/cardReduce/cardReduce.ctl.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="拟稿">
	        <component id="biaoti"  	renderType="normal" 	userId="" roleId="" deptId="" />
	        <component id="bianhao" 	renderType="normal" 	userId="" roleId="" deptId="" />
	        <component id="jhcd" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="ngrmc"		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="lxdh" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="ngrq" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngbm"	 	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="kpblsm" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="bz" 			renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT"  renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="ERP_RESULT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="cardReduceList" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" 	renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="file_list" 			renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="bianhao_button"    renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="fserp"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="sctz"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
        </state>
        <state id="组审核">
            <component id="biaoti"  	renderType="normal" 	userId="" roleId="" deptId="" />
	        <component id="bianhao"	 	renderType="normal" 	userId="" roleId="" deptId="" />
	        <component id="jhcd" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="ngrmc"		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="lxdh" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="ngrq" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngbm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="kpblsm" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="bz" 			renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT"  renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="ERP_RESULT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="cardReduceList" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" 	renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="file_list" 			renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="bianhao_button"    renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="fserp"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="sctz"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
        </state>
        <state id="经办人处理">
            <component id="biaoti"  	renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="bianhao" 	renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="jhcd" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngrmc"		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="lxdh" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngrq" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngbm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="kpblsm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="bz" 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ERP_RESULT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="cardReduceList" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" 	renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="file_list" 			renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="bianhao_button"    renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="fserp"  	  	renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="sctz"  	  	renderType="normal" 	userId="" roleId="" deptId="" />
        </state>
        <state id="readonly">
            <component id="biaoti" 	 	renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="bianhao" 	renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="jhcd" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngrmc"		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="lxdh" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngrq" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngbm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="kpblsm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="bz" 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ERP_RESULT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="cardReduceList" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" 	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="file_list" 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="bianhao_button"    renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="fserp"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="sctz"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
        </state>
        
        <state id="end">
            <component id="biaoti" 	 	renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="bianhao" 	renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="jhcd" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngrmc"		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="lxdh" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngrq" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngbm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="kpblsm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="bz" 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ERP_RESULT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="cardReduceList" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" 	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="file_list" 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="bianhao_button"    renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="fserp"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="sctz"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
        </state>
        <state id="did">
            <component id="biaoti" 	 	renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="bianhao" 	renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="jhcd" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngrmc"		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="lxdh" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngrq" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngbm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="kpblsm" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="bz" 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ERP_RESULT"  renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="cardReduceList" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" 	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="file_list" 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="bianhao_button"    renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="fserp"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="sctz"  	  	renderType="disable" 	userId="" roleId="" deptId="" />
        </state>
    </state-group>
</form-config>

=== gaowenhui/eam23/webroot/pages/eam2/zccz/evalKnow/evalKnow.ctl.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="拟稿">
	        <component id="biaoti" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="jhcd" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="scbh" renderType="normal" userId="" roleId="" deptId="" />
            <component id="lxdh" renderType="normal" userId="" roleId="" deptId="" />
            <component id="beizhu" renderType="normal" userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="all_Attachment" renderType="normal" userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="file_list" renderType="normal" userId="" roleId="" deptId="" />
        </state>
        <state id="组审核">
        	<component id="biaoti" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="jhcd" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="scbh" renderType="normal" userId="" roleId="" deptId="" />
            <component id="lxdh" renderType="normal" userId="" roleId="" deptId="" />
            <component id="beizhu" renderType="normal" userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="all_Attachment" renderType="normal" userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="file_list" renderType="normal" userId="" roleId="" deptId="" />
        </state>
         <state id="readonly">
         	<component id="biaoti" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="jhcd" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="scbh" renderType="disable" userId="" roleId="" deptId="" />
            <component id="lxdh" renderType="normal" userId="" roleId="" deptId="" />
            <component id="beizhu" renderType="normal" userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="all_Attachment" renderType="normal" userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="file_list" renderType="normal" userId="" roleId="" deptId="" />
        </state>
    </state-group>
</form-config>

=== gaowenhui/eam23/webroot/pages/eam2/zccz/know/know.ctl.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="拟稿">
        	<component id="biaoti" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="scbh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="ngbm" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="anniu" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="knowList" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="blyj_reason_list" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="file_list" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="banjie" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="组审核">
        	<component id="biaoti" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="scbh" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="anniu" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="knowList" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="blyj_reason_list" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="file_list" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="banjie" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="ngbm" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="readonly">
        	<component id="biaoti" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="scbh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="anniu" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="knowList" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blyj_reason_list" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="file_list" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="banjie" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="ngbm" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="did">
        	<component id="biaoti" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="scbh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="anniu" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="knowList" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blyj_reason_list" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="file_list" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="banjie" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="ngbm" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="end">
        	<component id="biaoti" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="scbh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="anniu" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="knowList" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blyj_reason_list" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="file_list" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="banjie" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="ngbm" renderType="disable" userId="" roleId="" deptId="" />
        </state>
    </state-group>
</form-config>

=== gaowenhui/eam23/webroot/pages/rdp4j/dynamicform/IndeedTheRight.ctl.xml
<?xml version="1.0"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="wf01">
	        <component id="button1" renderType="disable" userId="" roleId="" deptId="" />
	        <component id="button2" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="button3" renderType="normal" userId="" roleId="" deptId="" />
            <component id="title" renderType="readonly" userId="" roleId="" deptId="" />
            <component id="applyDate" renderType="normal" userId="" roleId="" deptId="" />
            <component id="applyDept" renderType="normal" userId="" roleId="" deptId="" />
            <component id="eventType" renderType="normal" userId="" roleId="" deptId="" />
            <component id="comments" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="wf02">
            <component id="button1" renderType="disable" userId="" roleId="" deptId="" />
            <component id="button2" renderType="disable" userId="" roleId="" deptId="" />
            <component id="button3" renderType="normal" userId="" roleId="" deptId="" />
            <component id="title" renderType="readonly" userId="" roleId="" deptId="" />
            <component id="applyDate" renderType="readonly" userId="" roleId="" deptId="" />
            <component id="applyDept" renderType="disable" userId="" roleId="" deptId="" />
            <component id="eventType" renderType="normal" userId="" roleId="" deptId="" />
            <component id="comments" renderType="normal" userId="" roleId="" deptId="" />
        </state>
        <state id="wf03">
            <component id="button1" renderType="disable" userId="" roleId="" deptId="" />
            <component id="button2" renderType="normal" userId="" roleId="" deptId="" />
            <component id="button3" renderType="disable" userId="" roleId="" deptId="" />
            <component id="title" renderType="disable" userId="" roleId="" deptId="" />
            <component id="applyDate" renderType="disable" userId="" roleId="" deptId="" />
            <component id="applyDept" renderType="readonly" userId="" roleId="" deptId="" />
            <component id="eventType" renderType="disable" userId="" roleId="" deptId="" />
            <component id="comments" renderType="readonly" userId="" roleId="" deptId="" />
        </state>
    </state-group>
</form-config>

=== gaowenhui/eam23/webroot/pages/eam2/hkgl/backConfirm/backConfirm.ctl.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="signTodo">
        	<component id="biaoti" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blbman" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blbm" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="dzje" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="dzrq" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkr" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkdbh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jzdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkdzt" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="zjly" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="qrxx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="MEETING_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="REMARK" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="HKQRXX" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="CONHK" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="TXQRD" renderType="normal" userId="" roleId="" deptId="" />
        </state>
        <state id="signDid">
        	<component id="biaoti" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blbman" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blbm" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="dzje" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="dzrq" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkr" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkdbh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jzdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkdzt" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="zjly" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="qrxx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="MEETING_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="REMARK" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="HKQRXX" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="CONHK" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="TXQRD" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="signEnd">
        	<component id="biaoti" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blbman" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blbm" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="dzje" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="dzrq" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkr" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkdbh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jzdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkdzt" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="zjly" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="qrxx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="MEETING_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="REMARK" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="HKQRXX" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="CONHK" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="TXQRD" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="readonly">
        	<component id="biaoti" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blbman" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="blbm" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="dzje" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="dzrq" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkr" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkdbh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jzdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="hkdzt" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="zjly" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="qrxx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="MEETING_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="REMARK" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="HKQRXX" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="CONHK" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="TXQRD" renderType="disable" userId="" roleId="" deptId="" />
        </state>
    </state-group>
</form-config>
