=== gaowenhui/eam23/webroot/pages/eam2/zccz/evalKnow/dynamic-form.dtd
<!ENTITY % Id "CDATA">
<!ENTITY % RenderType "(normal|readonly|disable)">
<!ENTITY % UserId "CDATA">
<!ENTITY % RoleId "CDATA">
<!ENTITY % DeptId "CDATA">

<!ELEMENT form-config (state-group) >

<!ELEMENT state-group (state*) >

<!ELEMENT state (component*) >
<!ATTLIST state         id               %Id;                #IMPLIED>

<!ELEMENT component (#PCDATA) >
<!ATTLIST component     id               %Id;                #IMPLIED>
<!ATTLIST component     renderType       %RenderType;        #IMPLIED>
<!ATTLIST component     userId           %UserId;            #IMPLIED>
<!ATTLIST component     roleId           %RoleId;            #IMPLIED>
<!ATTLIST component     deptId           %DeptId;            #IMPLIED>

=== gaowenhui/eam23/webroot/pages/eam2/zccz/meeting/xmIndex.ctl.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="会议组织">
        	<component id="spwys" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="hbrxm" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="yjhzrxm" renderType="readonly" userId="" roleId="" deptId="" />
        </state>
        <state id="did">
        	<component id="spwys" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="hbrxm" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="yjhzrxm" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="chooseSpwyCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseHbrCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseJcslxrCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseYjhzrCtl" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="end">
        	<component id="spwys" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="hbrxm" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="yjhzrxm" renderType="readonly" userId="" roleId="" deptId="" />
         	<component id="chooseSpwyCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseHbrCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseJcslxrCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseYjhzrCtl" renderType="disable" userId="" roleId="" deptId="" />       	
        </state>
        <state id="readonly">
        	<component id="spwys" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="hbrxm" renderType="readonly" userId="" roleId="" deptId="" />
        	<component id="yjhzrxm" renderType="readonly" userId="" roleId="" deptId="" />
         	<component id="chooseSpwyCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseHbrCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseJcslxrCtl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="chooseYjhzrCtl" renderType="disable" userId="" roleId="" deptId="" />       	
        </state>
    </state-group>
</form-config>

=== gaowenhui/eam23/webroot/pages/eam2/zccz/bld/stztczBld.ctl.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="合规审查">
        	<component id="czxmmc" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="CCzfs" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="czsbfs" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stywry" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jydx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stywyxzc" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfsh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="zcpgzWY" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stpgzWY" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="pgjg" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stxzName" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfName" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
            <component id="shitiList" renderType="normal" userId="" roleId="" deptId="" />
            <component id="BLYJ_ZZYJ" renderType="normal" userId="" roleId="96" deptId="" />
            <component id="BLYJ_THYJ" renderType="normal" userId="" roleId="" deptId="" />
            <component id="BLYJ_GCYJ" renderType="normal" userId="" roleId="" deptId="" />
            <component id="CHECK_DEPT_MODIFY" renderType="normal" userId="" roleId="" deptId="" />
            <component id="authority" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="did">
        	<component id="czxmmc" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="CCzfs" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="czsbfs" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stywry" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jydx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stywyxzc" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfsh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="zcpgzWY" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stpgzWY" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="pgjg" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stxzName" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfName" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
            <component id="shitiList" renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="BLYJ_ZZYJ" renderType="disable" userId="" roleId="96" deptId="" />
            <component id="BLYJ_THYJ" renderType="disable" userId="" roleId="" deptId="" />
            <component id="BLYJ_GCYJ" renderType="disable" userId="" roleId="" deptId="" />
            <component id="CHECK_DEPT_MODIFY" renderType="disable" userId="" roleId="" deptId="" />
            <component id="authority" renderType="normal" userId="" roleId="" deptId="" />
        </state>
        <state id="end">
            <component id="authority" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="czxmmc" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="CCzfs" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="czsbfs" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stywry" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jydx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stywyxzc" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfsh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="zcpgzWY" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stpgzWY" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="pgjg" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stxzName" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfName" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
            <component id="shitiList" renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="BLYJ_ZZYJ" renderType="disable" userId="" roleId="96" deptId="" />
            <component id="BLYJ_THYJ" renderType="disable" userId="" roleId="" deptId="" />
            <component id="BLYJ_GCYJ" renderType="disable" userId="" roleId="" deptId="" />
            <component id="CHECK_DEPT_MODIFY" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="readonly">
            <component id="authority" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="czxmmc" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="CCzfs" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="czsbfs" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stywry" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="jydx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stywyxzc" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfsh" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="zcpgzWY" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stpgzWY" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="pgjg" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="stxzName" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfName" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="DRAFT_DEPT" renderType="disable" userId="" roleId="" deptId="" />
            <component id="shitiList" renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="BLYJ_ZZYJ" renderType="disable" userId="" roleId="96" deptId="" />
            <component id="BLYJ_THYJ" renderType="disable" userId="" roleId="" deptId="" />
            <component id="BLYJ_GCYJ" renderType="disable" userId="" roleId="" deptId="" />
            <component id="CHECK_DEPT_MODIFY" renderType="disable" userId="" roleId="" deptId="" />
        </state>
    </state-group>
</form-config>

=== gaowenhui/eam23/webroot/pages/eam2/jygdzc/contract/contract.ctl.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="拟稿">
	        <component id="biaoti" renderType="normal" userId="" roleId="" deptId="" />
	         <component id="scbh" 		renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="jhcd" renderType="normal" userId="" roleId="" deptId="" />
            <component id="lxdh" renderType="normal" userId="" roleId="" deptId="" />
            <component id="jwlx" renderType="normal" userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="purchase_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="purchase_list_change" renderType="normal" userId="" roleId="" deptId="" />
            <component id="purchase_list_end" renderType="normal" userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="file_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="banjie" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="组审核">
	        <component id="biaoti" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="scbh" 		renderType="normal" 	userId="" roleId="" deptId="" />
	        <component id="ngbm" 		 			renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="jhcd" renderType="normal" userId="" roleId="" deptId="" />
	        <component id="ngrq" renderType="disable" userId="" roleId="" deptId="" />
            <component id="ngr" renderType="disable" userId="" roleId="" deptId="" />
            <component id="lxdh" renderType="normal" userId="" roleId="" deptId="" />
            <component id="ngbm" renderType="disable" userId="" roleId="" deptId="" />
            <component id="jwlx" renderType="disable" userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT" 		renderType="normal" 	userId="" roleId="" deptId="" />
            <component id="purchase_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="purchase_list_change" renderType="normal" userId="" roleId="" deptId="" />
            <component id="purchase_list_end" renderType="normal" userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="file_list" renderType="normal" userId="" roleId="" deptId="" />
            <component id="banjie" renderType="normal" userId="" roleId="" deptId="" />
        </state>
        <state id="readonly">
	        <component id="biaoti" renderType="disable" userId="" roleId="" deptId="" />
	         <component id="scbh" 		renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="bianhao" renderType="disable" userId="" roleId="" deptId="" />
	        <component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
	        <component id="ngrq" renderType="disable" userId="" roleId="" deptId="" />
	        <component id="ngbm" 		 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="ngr" renderType="disable" userId="" roleId="" deptId="" />
            <component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
            <component id="ngbm" renderType="disable" userId="" roleId="" deptId="" />
            <component id="jwlx" renderType="disable" userId="" roleId="" deptId="" />
            <component id="REMARK" renderType="disable" userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="purchase_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="purchase_list_change" renderType="disable" userId="" roleId="" deptId="" />
            <component id="purchase_list_end" renderType="disable" userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="file_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="banjie" renderType="disable" userId="" roleId="" deptId="" />
        </state>
         <state id="end">
	        <component id="biaoti" renderType="disable" userId="" roleId="" deptId="" />
	         <component id="scbh" 		renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="bianhao" renderType="disable" userId="" roleId="" deptId="" />
	        <component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
	        <component id="ngrq" renderType="disable" userId="" roleId="" deptId="" />
            <component id="ngr" renderType="disable" userId="" roleId="" deptId="" />
            <component id="ngbm" 		 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
            <component id="ngbm" renderType="disable" userId="" roleId="" deptId="" />
            <component id="jwlx" renderType="disable" userId="" roleId="" deptId="" />
            <component id="REMARK" renderType="disable" userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="purchase_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="purchase_list_change" renderType="disable" userId="" roleId="" deptId="" />
            <component id="purchase_list_end" renderType="disable" userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="file_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="banjie" renderType="disable" userId="" roleId="" deptId="" />
        </state>
         <state id="did">
	        <component id="biaoti" renderType="disable" userId="" roleId="" deptId="" />
	         <component id="scbh" 		renderType="disable" 	userId="" roleId="" deptId="" />
	        <component id="bianhao" renderType="disable" userId="" roleId="" deptId="" />
	        <component id="jhcd" renderType="disable" userId="" roleId="" deptId="" />
	        <component id="ngrq" renderType="disable" userId="" roleId="" deptId="" />
            <component id="ngr" renderType="disable" userId="" roleId="" deptId="" />
            <component id="lxdh" renderType="disable" userId="" roleId="" deptId="" />
            <component id="ngbm" renderType="disable" userId="" roleId="" deptId="" />
            <component id="jwlx" renderType="disable" userId="" roleId="" deptId="" />
            <component id="ngbm" 		 			renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="REMARK" renderType="disable" userId="" roleId="" deptId="" />
            <component id="DRAFT_DEPT" 		renderType="disable" 	userId="" roleId="" deptId="" />
            <component id="purchase_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="purchase_list_change" renderType="disable" userId="" roleId="" deptId="" />
            <component id="purchase_list_end" renderType="disable" userId="" roleId="" deptId="" />
            <component id="blyj_reason_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="file_list" renderType="disable" userId="" roleId="" deptId="" />
            <component id="banjie" renderType="disable" userId="" roleId="" deptId="" />
        </state>
    </state-group>
</form-config>

=== gaowenhui/eam23/webroot/pages/eam2/zccz/meeting/summarySuggestion.ctl.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE form-config SYSTEM "dynamic-form.dtd">
<form-config>
    <state-group>
        <state id="汇总审批意见">
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="APPROVEMENT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="SUMMARY_SUGGEST" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="endButton" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="spjl" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="sfba" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="czsx" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="fileButton" renderType="normal" userId="" roleId="" deptId="" />
        </state>
        <state id="审核汇总意见">
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="APPROVEMENT" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="SUMMARY_SUGGEST" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="endButton" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="spjl" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="sfba" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="czsx" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="fileButton" renderType="normal" userId="" roleId="" deptId="" />
        </state>
        <state id="业务运营组处理">
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="APPROVEMENT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="SUMMARY_SUGGEST" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="endButton" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="spjl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfba" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="czsx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="fileButton" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="公司领导批示">
        	<component id="LEADER" renderType="normal" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="APPROVEMENT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="SUMMARY_SUGGEST" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="endButton" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="spjl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfba" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="czsx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="fileButton" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="did">
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="APPROVEMENT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="SUMMARY_SUGGEST" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="endButton" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="spjl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfba" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="czsx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="fileButton" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="end">
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="APPROVEMENT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="SUMMARY_SUGGEST" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="endButton" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="spjl" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="sfba" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="czsx" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="fileButton" renderType="disable" userId="" roleId="" deptId="" />
        </state>
        <state id="readonly">
        	<component id="LEADER" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="OPERATION_GROUP" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="APPROVEMENT" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="SUMMARY_SUGGEST" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="endButton" renderType="disable" userId="" roleId="" deptId="" />
        	<component id="fileButton" renderType="disable" userId="" roleId="" deptId="" />
        </state>
    </state-group>
</form-config>
